import { GlassCard } from "../components/GlassCard";
import styles from "./About.module.css";

export default function About() {
  return (
    <div className={`${styles.aboutContainer} animate-fade-in`}>
      <h1 className={styles.titleFixed}>YourSounds</h1>

      <div className={styles.wrapper}>
        <GlassCard className={styles.card}>
          <h1 className={styles.header}>About YourSounds</h1>
          <p className={styles.introParagraph}>
            Welcome to YourSounds! Here, your voice steps into the spotlight and instantly 
            transforms into musical tones generated by real instruments. No complicated 
            settings — just say or hum something and hear it come alive.
          </p>

          <h2 className={styles.subHeader}>Applications</h2>
          <p className={styles.paragraph}>
            YourSounds can be used for:
          </p>
          <ul className={styles.list}>
            <li className={styles.listItem}>Creating unique musical compositions</li>
            <li className={styles.listItem}>Exploring the relationship between voice and music</li>
            <li className={styles.listItem}>Learning about sound and pitch in an interactive way</li>
            <li className={styles.listItem}>Just entertaining yourself (ps: Not everything has to be serious and for a reason)</li>
          </ul>

          <h2 className={styles.subHeader}>How It Works</h2>
          <p className={styles.paragraph}>
            The magic begins the moment your microphone picks up your voice. <strong>ml5.js</strong> listens in, 
            extracts the pitch and frequency behind every note you hum or speak, and turns them into clean musical data. 
            From there, <strong>Tone.js</strong> and <strong>soundfont-player</strong> step in, using that data to play back your melody on the 
            instrument of your choice, ready for you to tweak the speed, fine-tune the frequency, and make it truly yours.
          </p>

          <h2 className={styles.subHeader}>The Story</h2>
          <p className={styles.paragraph}>
            Being inclined towards music, I've always found myself humming random tones and little melodies, constantly 
            imagining how they would sound on an actual instrument — maybe even turning them into musical samples someday. 
            But I never had the skill to play those ideas on a real instrument, and I knew there were many others just like me. 
            That realisation led to the creation of YourSounds — a space where anyone can walk in with their creativity and 
            instantly turn their voice-driven ideas into musical reality.
          </p>
        </GlassCard>
      </div>
    </div>
  );
}
